on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: root
        key: ${{ secrets.KEY }}
        script: |
          sudo su
          cd /var/www/miranda-laravel
          git pull https://github.com/azerty0220pl/miranda-laravel.git
          php artisan --migrate
          composer install -n --no-plugins
          npm install
          systemctl restart apache2
    